version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: baitap6-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: baitap6-redis
    ports:
      - "6380:6379"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: baitap6-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "api_security_db"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mongodb_data:
  mysql_data:
